// Geliştirme aşamasında Supabase henüz kurulmadığı için (Gün 8) ekranları
// gerçek veriyle test edebilmek amacıyla oluşturulan mock veri seti.
// Gün 17'de Keşfet/Etkinlik Detay ekranları services/events.ts'teki
// gerçek Supabase sorgularına geçti. mockEvents hâlâ CalendarScreen.tsx
// tarafından kullanılıyor - takvimin gerçek veriye bağlanması Gün 36'da.
// mockUsers şu an hiçbir yerde kullanılmıyor.

import { Event, User } from '../types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    firstName: 'Ayşe',
    lastName: 'Yılmaz',
    username: 'ayseyilmaz',
    email: 'ayse@example.com',
    avatarUrl: null,
    bio: 'Etkinlik tutkunu',
    createdAt: '2026-01-05T10:00:00Z',
  },
  {
    id: 'u2',
    firstName: 'Mehmet',
    lastName: 'Kaya',
    username: 'mehmetkaya',
    email: 'mehmet@example.com',
    avatarUrl: null,
    bio: null,
    createdAt: '2026-01-08T14:30:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    organizerId: 'u1',
    title: 'Akustik Gece',
    description: 'Kadıköy sahilinde açık hava akustik müzik dinletisi.',
    category: 'muzik',
    date: '2026-08-20',
    time: '19:00',
    location: { address: 'Kadıköy, İstanbul', latitude: 40.9908, longitude: 29.0271 },
    capacity: 50,
    participantCount: 23,
    coverPhotoUrl: null,
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'e2',
    organizerId: 'u2',
    title: 'Sabah Koşusu',
    description: "Belgrad Ormanı'nda 10km grup koşusu.",
    category: 'spor',
    date: '2026-07-11',
    time: '07:30',
    location: { address: 'Belgrad Ormanı, İstanbul', latitude: 41.1868, longitude: 28.9994 },
    capacity: 30,
    participantCount: 30,
    coverPhotoUrl: null,
    createdAt: '2026-06-20T08:00:00Z',
  },
  {
    id: 'e3',
    organizerId: 'u1',
    title: 'Sokak Sanatları Atölyesi',
    description: 'Duvar resmi ve graffiti teknikleri üzerine başlangıç atölyesi.',
    category: 'sanat',
    date: '2026-08-22',
    time: '13:00',
    location: { address: 'Beyoğlu, İstanbul', latitude: 41.0345, longitude: 28.977 },
    capacity: 20,
    participantCount: 8,
    coverPhotoUrl: null,
    createdAt: '2026-08-03T11:15:00Z',
  },
  {
    id: 'e4',
    organizerId: 'u2',
    title: 'Dünya Mutfakları Buluşması',
    description: 'Herkesin bir yemek getirdiği potluck tarzı buluşma.',
    category: 'yemek',
    date: '2026-07-18',
    time: '18:30',
    location: { address: 'Beşiktaş, İstanbul', latitude: 41.0422, longitude: 29.0061 },
    capacity: 40,
    participantCount: 12,
    coverPhotoUrl: null,
    createdAt: '2026-06-25T16:45:00Z',
  },
  {
    id: 'e5',
    organizerId: 'u1',
    title: 'React Native Meetup',
    description: 'Mobil geliştiriciler için deneyim paylaşım etkinliği.',
    category: 'teknoloji',
    date: '2026-08-25',
    time: '18:00',
    location: { address: 'Maslak, İstanbul', latitude: 41.1105, longitude: 29.0217 },
    capacity: 60,
    participantCount: 45,
    coverPhotoUrl: null,
    createdAt: '2026-08-05T10:20:00Z',
  },
  {
    id: 'e6',
    organizerId: 'u2',
    title: 'Hızlı Okuma Semineri',
    description: 'Etkili okuma teknikleri ve pratik alıştırmalar.',
    category: 'egitim',
    date: '2026-07-14',
    time: '15:00',
    location: { address: 'Şişli, İstanbul', latitude: 41.0602, longitude: 28.9877 },
    capacity: 25,
    participantCount: 5,
    coverPhotoUrl: null,
    createdAt: '2026-06-22T13:00:00Z',
  },
  {
    id: 'e7',
    organizerId: 'u1',
    title: 'Caz Barında Jam Session',
    description: 'Müzisyenler ve dinleyiciler için doğaçlama caz gecesi.',
    category: 'muzik',
    date: '2026-08-08',
    time: '21:00',
    location: { address: 'Nişantaşı, İstanbul', latitude: 41.048, longitude: 28.9938 },
    capacity: 35,
    participantCount: 19,
    coverPhotoUrl: null,
    createdAt: '2026-08-06T09:30:00Z',
  },
  {
    id: 'e8',
    organizerId: 'u2',
    title: 'Basketbol Turnuvası',
    description: '3x3 amatör basketbol turnuvası, ödüllü.',
    category: 'spor',
    date: '2026-07-30',
    time: '10:00',
    location: { address: 'Ataşehir, İstanbul', latitude: 40.9923, longitude: 29.1244 },
    capacity: 48,
    participantCount: 32,
    coverPhotoUrl: null,
    createdAt: '2026-07-10T12:00:00Z',
  },
  {
    id: 'e9',
    organizerId: 'u1',
    title: 'Seramik Atölyesi',
    description: 'Çömlek çarkında ilk parçanı yapmayı öğren.',
    category: 'sanat',
    date: '2026-08-13',
    time: '11:00',
    location: { address: 'Moda, İstanbul', latitude: 40.9803, longitude: 29.028 },
    capacity: 15,
    participantCount: 15,
    coverPhotoUrl: null,
    createdAt: '2026-08-08T14:00:00Z',
  },
  {
    id: 'e10',
    organizerId: 'u2',
    title: 'Kahve Tadım Etkinliği',
    description: 'Farklı yöreden özel kahvelerin tadımı ve demleme teknikleri.',
    category: 'yemek',
    date: '2026-07-05',
    time: '16:00',
    location: { address: 'Karaköy, İstanbul', latitude: 41.0256, longitude: 28.9744 },
    capacity: 20,
    participantCount: 14,
    coverPhotoUrl: null,
    createdAt: '2026-06-15T17:30:00Z',
  },
  {
    id: 'e11',
    organizerId: 'u1',
    title: 'Girişimcilik Söyleşisi',
    description: 'Erken aşama girişimciler için deneyim paylaşımı ve networking.',
    category: 'egitim',
    date: '2026-08-27',
    time: '19:30',
    location: { address: 'Levent, İstanbul', latitude: 41.0814, longitude: 29.0107 },
    capacity: 70,
    participantCount: 51,
    coverPhotoUrl: null,
    createdAt: '2026-08-09T10:00:00Z',
  },
  {
    id: 'e12',
    organizerId: 'u2',
    title: 'Mobil Oyun Geliştirme Atölyesi',
    description: 'Unity ile ilk 2D oyununu bir günde tamamla.',
    category: 'teknoloji',
    date: '2026-07-23',
    time: '10:30',
    location: { address: 'Bakırköy, İstanbul', latitude: 40.9789, longitude: 28.8721 },
    capacity: 25,
    participantCount: 9,
    coverPhotoUrl: null,
    createdAt: '2026-07-01T15:10:00Z',
  },
];
