// Geliştirme aşamasında Supabase henüz kurulmadığı için (Gün 8) ekranları
// gerçek veriyle test edebilmek amacıyla oluşturulan mock veri seti.
// Gün 18'de bu veri, Supabase'den gelen `select` sorgusuyla değiştirilecektir.

import { Etkinlik, Kullanici } from '../types';

export const mockKullanicilar: Kullanici[] = [
  {
    id: 'u1',
    ad: 'Ayşe',
    soyad: 'Yılmaz',
    kullaniciAdi: 'ayseyilmaz',
    email: 'ayse@example.com',
    avatarUrl: null,
    bio: 'Etkinlik tutkunu',
    olusturulmaTarihi: '2026-01-05T10:00:00Z',
  },
  {
    id: 'u2',
    ad: 'Mehmet',
    soyad: 'Kaya',
    kullaniciAdi: 'mehmetkaya',
    email: 'mehmet@example.com',
    avatarUrl: null,
    bio: null,
    olusturulmaTarihi: '2026-01-08T14:30:00Z',
  },
];

export const mockEtkinlikler: Etkinlik[] = [
  {
    id: 'e1',
    organizatorId: 'u1',
    baslik: 'Akustik Gece',
    aciklama: 'Kadıköy sahilinde açık hava akustik müzik dinletisi.',
    kategori: 'muzik',
    tarih: '2026-08-20',
    saat: '19:00',
    konum: { adres: 'Kadıköy, İstanbul', enlem: 40.9908, boylam: 29.0271 },
    kapasite: 50,
    katilimciSayisi: 23,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-01T09:00:00Z',
  },
  {
    id: 'e2',
    organizatorId: 'u2',
    baslik: 'Sabah Koşusu',
    aciklama: "Belgrad Ormanı'nda 10km grup koşusu.",
    kategori: 'spor',
    tarih: '2026-08-16',
    saat: '07:30',
    konum: { adres: 'Belgrad Ormanı, İstanbul', enlem: 41.1868, boylam: 28.9994 },
    kapasite: 30,
    katilimciSayisi: 30,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-02T08:00:00Z',
  },
  {
    id: 'e3',
    organizatorId: 'u1',
    baslik: 'Sokak Sanatları Atölyesi',
    aciklama: 'Duvar resmi ve graffiti teknikleri üzerine başlangıç atölyesi.',
    kategori: 'sanat',
    tarih: '2026-08-22',
    saat: '13:00',
    konum: { adres: 'Beyoğlu, İstanbul', enlem: 41.0345, boylam: 28.977 },
    kapasite: 20,
    katilimciSayisi: 8,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-03T11:15:00Z',
  },
  {
    id: 'e4',
    organizatorId: 'u2',
    baslik: 'Dünya Mutfakları Buluşması',
    aciklama: 'Herkesin bir yemek getirdiği potluck tarzı buluşma.',
    kategori: 'yemek',
    tarih: '2026-08-18',
    saat: '18:30',
    konum: { adres: 'Beşiktaş, İstanbul', enlem: 41.0422, boylam: 29.0061 },
    kapasite: 40,
    katilimciSayisi: 12,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-04T16:45:00Z',
  },
  {
    id: 'e5',
    organizatorId: 'u1',
    baslik: 'React Native Meetup',
    aciklama: 'Mobil geliştiriciler için deneyim paylaşım etkinliği.',
    kategori: 'teknoloji',
    tarih: '2026-08-25',
    saat: '18:00',
    konum: { adres: 'Maslak, İstanbul', enlem: 41.1105, boylam: 29.0217 },
    kapasite: 60,
    katilimciSayisi: 45,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-05T10:20:00Z',
  },
  {
    id: 'e6',
    organizatorId: 'u2',
    baslik: 'Hızlı Okuma Semineri',
    aciklama: 'Etkili okuma teknikleri ve pratik alıştırmalar.',
    kategori: 'egitim',
    tarih: '2026-08-19',
    saat: '15:00',
    konum: { adres: 'Şişli, İstanbul', enlem: 41.0602, boylam: 28.9877 },
    kapasite: 25,
    katilimciSayisi: 5,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-05T13:00:00Z',
  },
  {
    id: 'e7',
    organizatorId: 'u1',
    baslik: 'Caz Barında Jam Session',
    aciklama: 'Müzisyenler ve dinleyiciler için doğaçlama caz gecesi.',
    kategori: 'muzik',
    tarih: '2026-08-23',
    saat: '21:00',
    konum: { adres: 'Nişantaşı, İstanbul', enlem: 41.048, boylam: 28.9938 },
    kapasite: 35,
    katilimciSayisi: 19,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-06T09:30:00Z',
  },
  {
    id: 'e8',
    organizatorId: 'u2',
    baslik: 'Basketbol Turnuvası',
    aciklama: '3x3 amatör basketbol turnuvası, ödüllü.',
    kategori: 'spor',
    tarih: '2026-08-30',
    saat: '10:00',
    konum: { adres: 'Ataşehir, İstanbul', enlem: 40.9923, boylam: 29.1244 },
    kapasite: 48,
    katilimciSayisi: 32,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-07T12:00:00Z',
  },
  {
    id: 'e9',
    organizatorId: 'u1',
    baslik: 'Seramik Atölyesi',
    aciklama: 'Çömlek çarkında ilk parçanı yapmayı öğren.',
    kategori: 'sanat',
    tarih: '2026-08-21',
    saat: '11:00',
    konum: { adres: 'Moda, İstanbul', enlem: 40.9803, boylam: 29.028 },
    kapasite: 15,
    katilimciSayisi: 15,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-08T14:00:00Z',
  },
  {
    id: 'e10',
    organizatorId: 'u2',
    baslik: 'Kahve Tadım Etkinliği',
    aciklama: 'Farklı yöreden özel kahvelerin tadımı ve demleme teknikleri.',
    kategori: 'yemek',
    tarih: '2026-08-17',
    saat: '16:00',
    konum: { adres: 'Karaköy, İstanbul', enlem: 41.0256, boylam: 28.9744 },
    kapasite: 20,
    katilimciSayisi: 14,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-08T17:30:00Z',
  },
  {
    id: 'e11',
    organizatorId: 'u1',
    baslik: 'Girişimcilik Söyleşisi',
    aciklama: 'Erken aşama girişimciler için deneyim paylaşımı ve networking.',
    kategori: 'egitim',
    tarih: '2026-08-27',
    saat: '19:30',
    konum: { adres: 'Levent, İstanbul', enlem: 41.0814, boylam: 29.0107 },
    kapasite: 70,
    katilimciSayisi: 51,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-09T10:00:00Z',
  },
  {
    id: 'e12',
    organizatorId: 'u2',
    baslik: 'Mobil Oyun Geliştirme Atölyesi',
    aciklama: 'Unity ile ilk 2D oyununu bir günde tamamla.',
    kategori: 'teknoloji',
    tarih: '2026-08-29',
    saat: '10:30',
    konum: { adres: 'Bakırköy, İstanbul', enlem: 40.9789, boylam: 28.8721 },
    kapasite: 25,
    katilimciSayisi: 9,
    kapakFotoUrl: null,
    olusturulmaTarihi: '2026-08-10T15:10:00Z',
  },
];
